### ISSUE TITLE
[Bug] Reset automatically after prefix isn't working

### ISSUE THREAD

**Issue by Paulie9990** [dmulloy2/SwornPermissions#2]
SwornPermissions Version: 1.0-b331
Spigot: git-Spigot-1e4dd71-4507d99 (1.10.2)

In config.yml I have "forceReset:" set to true, however, upon setting a prefix it does not reset without manually using &r.

**Comment by dmulloy2** [comment]
Thank you for the report. I need some more information. Can you provide your full config.yml via [pastebin](pastebin.com)?

**Comment by Paulie9990** [comment]
http://pastebin.com/wyW8gwnZ

**Comment by Paulie9990** [comment]
Actually, it seems to have fixed itself. After I installed essentialsx it works fine
